const express = require('express');
const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');

const { ApiError } = require('../../errors');
const { asyncHandler } = require('../../middleware/asyncHandler');
const {
  fetchTransaction,
  fetchPaymentsForTransaction,
} = require('../../services/stellarService');

const router = express.Router();

const TX_HASH_RE = /^[a-fA-F0-9]{64}$/;


/**
 * @openapi
 * /receipts/:txHash:
 *   get:
 *     tags:
 *       - v1
 *     description: GET /receipts/:txHash
 *     responses:
 *       200:
 *         description: Success
 */
router.get('/receipts/:txHash', asyncHandler(async (req, res, next) => {
  const { txHash } = req.params;

  if (!TX_HASH_RE.test(txHash)) {
    return next(new ApiError('INVALID_INPUT', 'Invalid transaction hash format'));
  }

  let tx;
  let paymentOps;

  try {
    [tx, paymentOps] = await Promise.all([
      fetchTransaction(txHash),
      fetchPaymentsForTransaction(txHash),
    ]);
  } catch (err) {
    if (err?.code === 'EOPENBREAKER') {
      return next(new ApiError('SERVICE_UNAVAILABLE', 'Stellar Horizon is temporarily unavailable; please try again later'));
    }
    if (err && err.response && err.response.status === 404) {
      return next(new ApiError('NOT_FOUND', 'Transaction not found'));
    }
    return next(
      new ApiError('UPSTREAM_ERROR', 'Failed to fetch transaction from Horizon', { cause: err }),
    );
  }

  const timestamp = tx.created_at
    ? new Date(tx.created_at).toUTCString()
    : 'Unknown';

  const nativeOp = (paymentOps.records || []).find(
    (op) => op.asset_type === 'native',
  );

  const sender = nativeOp ? nativeOp.from : tx.source_account;
  const receiver = nativeOp ? nativeOp.to : 'Contract invocation';
  const amount = nativeOp ? `${nativeOp.amount} XLM` : 'See Stellar Explorer';

  const safeHash = txHash.replace(/[^a-fA-F0-9]/g, '');
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="receipt-${safeHash}.pdf"`,
  );

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc
    .fontSize(20)
    .text('Stellar Transaction Receipt', { align: 'center' })
    .moveDown(1.5);

  doc.fontSize(11).text(`Transaction Hash: ${txHash}`).moveDown(0.5);
  doc.text(`Timestamp:        ${timestamp}`).moveDown(0.5);
  doc.text(`Sender:           ${sender}`).moveDown(0.5);
  doc.text(`Receiver:         ${receiver}`).moveDown(0.5);
  doc.text(`Amount:           ${amount}`).moveDown(1.5);

  try {
    const txUrl = `https://stellar.expert/explorer/testnet/tx/${txHash}`;
    const qrBuffer = await QRCode.toBuffer(txUrl);
    const qrSize = 100;
    const xPosition = (doc.page.width - qrSize) / 2;
    doc.image(qrBuffer, xPosition, doc.y, { width: qrSize, height: qrSize });
    doc.y += qrSize + 20;
  } catch (err) {
    console.error('Failed to generate QR code', err);
  }

  doc.fontSize(9).fillColor('#888888').text('Generated by Stellar Pay — Testnet', {
    align: 'center',
  });

  doc.end();
}));

module.exports = router;
